### ISSUE TITLE
Sync error reported by android, not by Flock

### ISSUE THREAD

**Issue by bungabunga** [WhisperSystems/Flock#83]
i installed Flock yesterday and sync it with the server. my device is telling me that there is an error by Flock syncing contacts (last sync: yesterday evening) but if i go to Flock it wellcomes me with "Everything's working! (last sync: today morning)"

here is a log that i took just after an (un)successful sync:
https://gist.github.com/c070cb3f56c997a9a5e8

**Comment by nysatrok** [comment]
I experience the same issue. There might be a server-side limit on the size of a single contact. This is just a wild guess.

@rhodey Is there such a limit? Can this issue be related to that?

**Comment by n1m1** [comment]
Same issue here.

**Comment by nysatrok** [comment]
The issue still occurs under 0.9.6 and Android 5.0.2 but now I get a different error message:

    who knows...
    org.apache.commons.httpclient.NoHttpResponseException: The server flock-sync.whispersystems.org failed to respond
        at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:1976)
        at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1735)
        at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:346)
        at org.anhonesteffort.flock.webdav.DavClient.execute(DavClient.java:118)
        at org.anhonesteffort.flock.webdav.AbstractDavComponentCollection.getComponents(AbstractDavComponentCollection.java:384)
        at org.anhonesteffort.flock.sync.addressbook.HidingCardDavCollection.getHiddenComponents(HidingCardDavCollection.java:183)
        at org.anhonesteffort.flock.sync.AbstractDavSyncWorker.pullRemotelyChangedComponents(AbstractDavSyncWorker.java:551)
        at org.anhonesteffort.flock.sync.AbstractDavSyncWorker.run(AbstractDavSyncWorker.java:122)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)

@bungabunga @n1m1 Can you confirm this?

**Comment by bungabunga** [comment]
i can't confirm because i have a new phone now and flock works without issues. but the old one had many issues..

**Comment by nysatrok** [comment]
The issue may or may not occur with the same set of contacts. It is more likely to occur if many contacts have been imported at once. That's weird.
